# Generated by Django 5.1.4 on 2024-12-23 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('subject', models.CharField(choices=[('lesson', 'Lesson'), ('course', 'Course')], max_length=6)),
                ('amount', models.IntegerField()),
                ('pay_method', models.CharField(choices=[('transfer', 'Transfer'), ('cash', 'Cash')], max_length=8)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='materials.course')),
                ('lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='materials.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
